### Ex 4-1

CalcTest.java

```java
package junitTests;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.Assert.*;
import static org.junit.Assert.fail;

import org.junit.jupiter.api.Test;

class CalcTest {

	   @Test public void testAdd()
	   {
	      assertTrue ("Calc sum incorrect", 5 == Calc.add (2, 3));
	   }
	   
	   @Test public void testSubstract()
	   {
	      assertTrue ("Calc substraction incorrect", -1 == Calc.substract (2, 3));
	   }
	   
	   @Test public void testMultiply()
	   {
	      assertTrue ("Calc multiplication incorrect", 6 == Calc.multiply (2, 3));
	   }
	   
	   @Test public void testDivide()
	   {
		  try {
			  assertTrue ("Calc sum incorrect", 0.00001 == Calc.divide (1, 100000));  
		  }
		  catch(ArithmeticException e) {
			  return;
		  }
		  fail("ArithmeticException expected");
	   }

}
```

Calc.java

```java
package junitTests;

public class Calc {   

	static public int add (int a, int b)
	{
		return a + b;
	}	
	
	static public int substract(int a, int b)
	{
		return a - b;
	}
	
	static public int multiply(int a, int b) {
		return a * b;
	}
	
	static public int divide(int a, int b) {
		if(b == 0) throw new ArithmeticException("Calc.divide");
		int c = a / b;
		if(a != 0 && c == 0) throw new ArithmeticException("Calc.divide");

		return c;
	}
}
```
